title: FlowState Documentation
description: High-performance node editor for Blazor
theme: just-the-docs
color_scheme: dark

# Base URL for GitHub Pages
baseurl: "/FlowState"
url: "https://sps014.github.io"

# Navigation structure
nav_sort: case_insensitive

# Syntax highlighting
highlighter: rouge
markdown: kramdown

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "FlowState on GitHub":
    - "https://github.com/sps014/FlowState"
  "NuGet Package":
    - "https://www.nuget.org/packages/FlowState"

# Footer content
footer_content: "Copyright &copy; 2025 FlowState. Distributed under the MIT License."

# Color scheme
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

