name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore examples/FlowStateBlazorWasm/FlowStateBlazorWasm.csproj

      - name: Build
        run: dotnet build examples/FlowStateBlazorWasm/FlowStateBlazorWasm.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish examples/FlowStateBlazorWasm/FlowStateBlazorWasm.csproj -c Release -o publish

      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/FlowState\/" \/>/g' publish/wwwroot/index.html

      - name: Ensure crossorigin attribute on script tags
        run: |
          sed -i 's/<script src="_framework\/blazor\.webassembly\([^"]*\)\.js"><\/script>/<script src="_framework\/blazor.webassembly\1.js" crossorigin="anonymous"><\/script>/g' publish/wwwroot/index.html
          sed -i 's/<script src="_framework\/blazor\.webassembly\([^"]*\)\.js" crossorigin="anonymous" crossorigin="anonymous">/<script src="_framework\/blazor.webassembly\1.js" crossorigin="anonymous">/g' publish/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll

      - name: Add 404.html for SPA routing
        run: cp publish/wwwroot/index.html publish/wwwroot/404.html

      - name: Add custom headers for WASM and compression
        run: |
          cat > publish/wwwroot/.htaccess << 'EOF'
          # Enable CORS for WebAssembly
          <FilesMatch "\.(wasm|dll|pdb|dat)$">
            Header set Access-Control-Allow-Origin "*"
          </FilesMatch>
          
          # Proper MIME types
          AddType application/wasm .wasm
          AddType application/octet-stream .dll
          AddType application/octet-stream .dat
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'publish/wwwroot'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

