name: Publish to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/FlowState/FlowState.csproj
      
    - name: Build
      run: dotnet build src/FlowState/FlowState.csproj --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack src/FlowState/FlowState.csproj --configuration Release --no-build --output ./artifacts -p:PackageVersion=${{ github.event.inputs.version }}
      
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg

